global using MediatR;
global using Microsoft.AspNetCore.Http.Json;
global using Microsoft.EntityFrameworkCore;
global using SEORankTracker.App.Server.Extensions;
global using SEORankTracker.Database;
global using SEORankTracker.Logic.Utilities;
global using SEORankTracker.Shared.Requests;
global using SEORankTracker.Shared.Responses;
global using System.Reflection;
